// Employee001 — shared data exports

export type IntegrationStatus =
  | "connected"
  | "syncing"
  | "needs-auth"
  | "disconnected";

export type Integration = {
  id: string;
  name: string;
  category: string;
  desc: string;
  scopes: string[];
  status: IntegrationStatus;
  lastSync: string;
  events: number;
  owner: string;
  pinned?: boolean;
  composioSlug?: string; // Composio catalog slug when it differs from id
};

export const INTEGRATIONS: Integration[] = [
  {
    id: "outlook",
    name: "Outlook",
    category: "Email",
    desc: "Inbox patterns, threads, response cadence",
    scopes: ["Mail.Read", "Mail.ReadBasic"],
    status: "connected",
    lastSync: "12 min ago",
    events: 3421,
    owner: "Microsoft",
  },
  {
    id: "gmail",
    name: "Gmail",
    category: "Email",
    desc: "Inbox patterns, threads, response cadence",
    scopes: ["gmail.readonly"],
    status: "connected",
    lastSync: "8 min ago",
    events: 2890,
    owner: "Google",
  },
  {
    id: "teams",
    name: "MS Teams",
    category: "Meetings",
    desc: "Meeting transcripts, channel activity",
    scopes: ["ChannelMessage.Read"],
    status: "connected",
    lastSync: "2 hr ago",
    events: 412,
    owner: "Microsoft",
    composioSlug: "microsoft_teams",
  },
  {
    id: "meet",
    name: "Meet",
    category: "Meetings",
    desc: "Calendar events and meeting transcripts",
    scopes: ["calendar.readonly"],
    status: "connected",
    lastSync: "31 min ago",
    events: 187,
    owner: "Google",
    composioSlug: "googlemeet",
  },
  {
    id: "zoom",
    name: "Zoom",
    category: "Meetings",
    desc: "Meeting transcripts and recordings",
    scopes: ["meeting:read", "recording:read"],
    status: "needs-auth",
    lastSync: "—",
    events: 0,
    owner: "Zoom",
  },
  {
    id: "slack",
    name: "Slack",
    category: "Chat",
    desc: "Channels, DMs, threads — twin output channel",
    scopes: ["channels:history", "chat:write"],
    status: "connected",
    lastSync: "live",
    events: 8417,
    owner: "Slack",
    pinned: true,
  },
  {
    id: "github",
    name: "GitHub",
    category: "Engineering",
    desc: "PRs, reviews, issues, discussions",
    scopes: ["repo", "read:org"],
    status: "connected",
    lastSync: "4 min ago",
    events: 1204,
    owner: "GitHub",
  },
  {
    id: "linear",
    name: "Linear",
    category: "Engineering",
    desc: "Issues, projects, comments",
    scopes: ["read"],
    status: "syncing",
    lastSync: "Initial sync…",
    events: 89,
    owner: "Linear",
  },
  {
    id: "jira",
    name: "Jira",
    category: "Engineering",
    desc: "Issues, sprints, comments",
    scopes: ["read:jira-work"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Atlassian",
  },
  {
    id: "sharepoint",
    name: "SharePoint",
    category: "Microsoft 365",
    desc: "Docs, wikis, shared knowledge base",
    scopes: ["Sites.Read.All"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Microsoft",
    composioSlug: "share_point",
  },
  {
    id: "onedrive",
    name: "OneDrive",
    category: "Microsoft 365",
    desc: "Files, documents, version history",
    scopes: ["Files.Read.All"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Microsoft",
    composioSlug: "one_drive",
  },
  {
    id: "loop",
    name: "Microsoft Loop",
    category: "Microsoft 365",
    desc: "Collaborative workspaces and components",
    scopes: ["Loop.Read.All"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Microsoft",
  },
  {
    id: "planner",
    name: "Planner",
    category: "Microsoft 365",
    desc: "Tasks, assignments, project buckets",
    scopes: ["Tasks.Read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Microsoft",
  },

  // ─── Work Management ──────────────────────────────────────────────────
  {
    id: "asana",
    name: "Asana",
    category: "Work Management",
    desc: "Projects, tasks, comments, assignees",
    scopes: ["projects.read", "tasks.read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Asana",
  },
  {
    id: "clickup",
    name: "ClickUp",
    category: "Work Management",
    desc: "Spaces, lists, tasks, comments",
    scopes: ["read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "ClickUp",
  },
  {
    id: "monday",
    name: "Monday",
    category: "Work Management",
    desc: "Boards, items, updates",
    scopes: ["boards:read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "monday.com",
  },
  {
    id: "trello",
    name: "Trello",
    category: "Work Management",
    desc: "Boards, lists, cards, comments",
    scopes: ["read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Atlassian",
  },
  {
    id: "airtable",
    name: "Airtable",
    category: "Work Management",
    desc: "Bases, tables, records",
    scopes: ["data.records:read", "schema.bases:read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Airtable",
  },

  // ─── Knowledge / Docs ─────────────────────────────────────────────────
  {
    id: "notion",
    name: "Notion",
    category: "Knowledge",
    desc: "Pages, databases, comments — long-form thinking",
    scopes: ["read_content"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Notion",
  },
  {
    id: "confluence",
    name: "Confluence",
    category: "Knowledge",
    desc: "Wiki pages, spaces, comments",
    scopes: ["read:confluence-content.all"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Atlassian",
  },
  {
    id: "coda",
    name: "Coda",
    category: "Knowledge",
    desc: "Docs, tables, formulas",
    scopes: ["read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Coda",
  },
  {
    id: "google-docs",
    name: "Google Docs",
    category: "Knowledge",
    desc: "Documents, comments, version history",
    scopes: ["documents.readonly"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Google",
    composioSlug: "googledocs",
  },
  {
    id: "google-sheets",
    name: "Google Sheets",
    category: "Knowledge",
    desc: "Spreadsheets, ranges, comments",
    scopes: ["spreadsheets.readonly"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Google",
    composioSlug: "googlesheets",
  },

  // ─── CRM / Sales ──────────────────────────────────────────────────────
  {
    id: "salesforce",
    name: "Salesforce",
    category: "CRM",
    desc: "Accounts, opportunities, activity history",
    scopes: ["api", "refresh_token"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Salesforce",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    category: "CRM",
    desc: "Contacts, deals, conversations",
    scopes: ["crm.objects.contacts.read", "crm.objects.deals.read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "HubSpot",
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    category: "CRM",
    desc: "Pipelines, deals, activities",
    scopes: ["deals:read", "activities:read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Pipedrive",
  },

  // ─── Support ──────────────────────────────────────────────────────────
  {
    id: "zendesk",
    name: "Zendesk",
    category: "Support",
    desc: "Tickets, conversations, macros",
    scopes: ["read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Zendesk",
  },
  {
    id: "intercom",
    name: "Intercom",
    category: "Support",
    desc: "Conversations, contacts, articles",
    scopes: ["read_conversations", "read_users"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Intercom",
  },

  // ─── Design ───────────────────────────────────────────────────────────
  {
    id: "figma",
    name: "Figma",
    category: "Design",
    desc: "Files, comments, components",
    scopes: ["files:read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Figma",
  },
  {
    id: "miro",
    name: "Miro",
    category: "Design",
    desc: "Boards, frames, sticky-note clusters",
    scopes: ["boards:read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Miro",
  },

  // ─── Files / Storage ──────────────────────────────────────────────────
  {
    id: "google-drive",
    name: "Google Drive",
    category: "Files",
    desc: "Files, folders, version history",
    scopes: ["drive.readonly"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Google",
    composioSlug: "googledrive",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    category: "Files",
    desc: "Files, shared folders, comments",
    scopes: ["files.metadata.read", "files.content.read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Dropbox",
  },
  {
    id: "box",
    name: "Box",
    category: "Files",
    desc: "Files, folders, collaborators",
    scopes: ["root_readwrite"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Box",
  },

  // ─── Calendar (separate from Meetings — Google Calendar covers more) ─
  {
    id: "google-calendar",
    name: "Google Calendar",
    category: "Calendar",
    desc: "Events, attendees, recurrence",
    scopes: ["calendar.events.readonly"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Google",
    composioSlug: "googlecalendar",
  },

  // ─── Engineering (add alongside GitHub / Linear / Jira) ──────────────
  {
    id: "gitlab",
    name: "GitLab",
    category: "Engineering",
    desc: "MRs, issues, pipelines, comments",
    scopes: ["read_api"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "GitLab",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    category: "Engineering",
    desc: "Pull requests, issues, comments",
    scopes: ["repository:read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Atlassian",
  },

  // ─── Chat (add alongside Slack) ───────────────────────────────────────
  {
    id: "discord",
    name: "Discord",
    category: "Chat",
    desc: "Servers, channels, messages",
    scopes: ["bot", "messages.read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Discord",
  },

  // ─── Marketing ────────────────────────────────────────────────────────
  {
    id: "mailchimp",
    name: "Mailchimp",
    category: "Marketing",
    desc: "Audiences, campaigns, automations",
    scopes: ["read"],
    status: "disconnected",
    lastSync: "—",
    events: 0,
    owner: "Mailchimp",
  },
];

export type ProfileFileStatus = "done" | "running" | "queued";

export type ProfileFile = {
  name: string;
  desc: string;
  tokens: number;
  status: ProfileFileStatus;
};

export const PROFILE_FILES: ProfileFile[] = [
  { name: "EXPERTISE.md", desc: "Domains the expert is authoritative on", tokens: 4218, status: "done" },
  { name: "TONE.md", desc: "Voice, register, characteristic phrases", tokens: 2104, status: "done" },
  { name: "CONTEXT.md", desc: "Org chart, team, stakeholders, projects", tokens: 3876, status: "done" },
  { name: "DECISIONS.md", desc: "Past decisions and the reasoning behind them", tokens: 5102, status: "running" },
  { name: "PREFERENCES.md", desc: "Tools, formats, escalation thresholds", tokens: 1820, status: "running" },
  { name: "PEOPLE.md", desc: "Who the expert defers to and on what", tokens: 2987, status: "queued" },
  { name: "RECURRING.md", desc: "Frequently asked questions and stock answers", tokens: 0, status: "queued" },
  { name: "BOUNDARIES.md", desc: "What the twin should NEVER answer alone", tokens: 0, status: "queued" },
  { name: "PROJECTS.md", desc: "Active workstreams and their current state", tokens: 0, status: "queued" },
  { name: "WORKING_STYLE.md", desc: "Hours, async preferences, meeting style", tokens: 0, status: "queued" },
  { name: "GLOSSARY.md", desc: "Internal acronyms, codenames, jargon", tokens: 0, status: "queued" },
  { name: "ESCALATION.md", desc: "Who to route to when twin lacks confidence", tokens: 0, status: "queued" },
  { name: "HISTORY.md", desc: "Role timeline, promotions, recognition, training", tokens: 1840, status: "done" },
];
