/**
 * Shared contract for the Twin Memory Graph feature.
 * Stable surface used by:
 *   - src/lib/ex-profile-files.ts  (data layer — frontmatter, wikilinks, backlinks)
 *   - src/lib/skills/*             (skills the twin runner can call)
 *   - src/lib/twin-runner.ts       (orchestration)
 *   - src/app/api/twin/chat/...    (SSE endpoint emitting TwinTraceEvent)
 *   - src/app/(workspace)/flow/... (Memory Graph UI)
 *
 * Do NOT edit this file without coordinating across all consumers.
 */

// ─── Frontmatter (Obsidian-style typed properties) ───────────────────────────

export type ProfileSourceTag =
  | "github"
  | "slack"
  | "linear"
  | "jira"
  | "gmail"
  | "outlook"
  | "zoom"
  | "meet"
  | "teams";

export type FrontmatterTag =
  | "draft"
  | "needs-human-review"
  | "stable"
  | "stale"
  | "high-confidence";

export type Frontmatter = {
  /** 0–1, how confident the twin is when answering from this file */
  confidence: number;
  /** ISO date string */
  last_updated: string;
  /** Which connectors fed this file */
  sources: ProfileSourceTag[];
  /** Other profile filenames this file references (resolved from [[wikilinks]]) */
  linked_files: string[];
  /** Free-form tags for UI filtering */
  tags: FrontmatterTag[];
};

// ─── Wikilinks ───────────────────────────────────────────────────────────────

/** A parsed `[[FILENAME.md]]` reference inside a profile file's content. */
export type WikiLink = {
  /** The target file's full name, e.g. "BOUNDARIES.md" */
  target: string;
  /** Optional anchor / heading inside the target — `[[X.md#section]]` */
  anchor?: string;
  /** Optional display label — `[[X.md|alias]]` */
  alias?: string;
};

// ─── Trace events (streamed from the chat endpoint) ──────────────────────────

/** A single event in the twin's reasoning trace. The chat endpoint emits these
 *  as Server-Sent Events (`data: ${JSON.stringify(event)}\n\n`). */
export type TwinTraceEvent =
  | {
      type: "tool_call";
      /** Skill name, e.g. "read_profile_file" */
      name: string;
      args: Record<string, unknown>;
      /** Monotonic ms since stream start, for animation timing */
      ts: number;
    }
  | {
      type: "tool_result";
      name: string;
      /** Short human-readable summary, e.g. "Read 4.2k tokens from DECISIONS.md" */
      summary: string;
      /** Files that were touched — drives node highlighting in the graph */
      files: string[];
      ts: number;
    }
  | {
      type: "text_delta";
      delta: string;
      ts: number;
    }
  | {
      type: "cite";
      /** A file the final answer cites — drives the persistent "cited" highlight */
      file: string;
      ts: number;
    }
  | {
      type: "skill_recall";
      skills: Array<{
        id: string;
        label: string;
        description: string;
      }>;
      ts: number;
    }
  | {
      type: "done";
      confidence: number;
      cited_files: string[];
      ts: number;
    }
  | {
      type: "tool_approval_request";
      approvalId: string;
      tool: string;
      label: string;
      input: Record<string, unknown>;
      reason: string;
      ts: number;
    }
  | {
      type: "tool_approval_resolved";
      approvalId: string;
      decision: "allow" | "deny";
      ts: number;
    }
  | {
      type: "tool_blocked";
      tool: string;
      reason: string;
      ts: number;
    }
  | {
      /** brain_recall is emitted by the chat + task routes when org-brain nodes were matched. */
      type: "brain_recall";
      nodes: Array<{ slug: string; label: string; type: string; description: string }>;
      ts: number;
    }
  | {
      /** Emitted when the restrictWriteToScratch hook denies a Write call.
       *  Gives the CEO visibility into why the twin's memo wasn't saved. */
      type: "scratch_write_denied";
      reason: string;
      ts: number;
    }
  | {
      /** SDK session id for this run — client should persist and pass back on the next turn. */
      type: "session";
      sessionId: string;
      ts: number;
    }
  | {
      type: "artifact";
      artifactId: string;
      payload: {
        type: "html" | "svg";
        title: string;
        content: string;
      };
      ts: number;
    }
  | {
      /** External-service failure surfaced to the UI so the user sees a real
       *  message instead of a silent empty bubble. `kind` lets the UI distinguish
       *  e.g. "anthropic_unavailable" (the model is offline) from
       *  "composio_degraded" (tools missing, but the twin can still answer). */
      type: "error";
      kind: "anthropic_unavailable" | "composio_degraded" | "internal";
      message: string;
      ts: number;
    }
  | {
      /** Twin called AskUserQuestion — the run is paused on a promise keyed
       *  by approvalId. The UI renders the question stack as preview cards
       *  and POSTs the answers map back to `/api/council/approve` to resume. */
      type: "clarification_request";
      approvalId: string;
      questions: Array<{
        question: string;
        header: string;
        multiSelect: boolean;
        options: Array<{ label: string; description: string; preview?: string }>;
      }>;
      ts: number;
    }
  | {
      /** Sent right after the CEO submits their answers. The UI uses this to
       *  drop the clarification card from the message before the model's next
       *  text_delta lands. */
      type: "clarification_resolved";
      approvalId: string;
      ts: number;
    };

// ─── Skills (Paperclip-style typed tools) ────────────────────────────────────

/** A skill the twin runner can call. The runner exposes these to the LLM as
 *  Anthropic tool-use tools and dispatches handler() when the model picks one. */
export type Skill<TInput = Record<string, unknown>, TOutput = unknown> = {
  /** Unique snake_case name, used as the tool name in tool-use */
  name: string;
  /** One-line description shown to the model */
  description: string;
  /** JSON Schema for the input. Keep it minimal; the model is good at filling it. */
  input_schema: {
    type: "object";
    properties: Record<string, unknown>;
    required?: string[];
  };
  /** Server-side implementation */
  handler: (input: TInput) => Promise<TOutput> | TOutput;
};
