import fs from "fs";
import path from "path";

// ─── Types ────────────────────────────────────────────────────────────────────

export type TaskStatus = "running" | "complete" | "error" | "aborted";

export type TaskRun = {
  id: string;                  // matches the runId used in audit-log entries
  employeeId: string;
  employeeName: string;
  task: string;                // original task text from the CEO
  startedAt: string;           // ISO
  endedAt?: string;            // ISO, set on completion
  status: TaskStatus;
  finalText?: string;          // accumulated text output
  toolCalls: number;
  approvalsRequested: number;
  approvalsApproved: number;
  approvalsDenied: number;
  blockedTools: number;
  confidence?: number;
  turns?: number;
  errorMessage?: string;
  costUsd?: number;        // Actual API spend (from SDK total_cost_usd)
  budgetUsd?: number;      // Hard cap that was applied to this run
  stoppedReason?: "max_budget" | "max_turns" | "natural";
};

export type TaskEvent = {
  ts: number;                  // ms since task start
  // Mirrors the SSE event types emitted by /api/employees/[id]/task
  type:
    | "start"
    | "text_delta"
    | "artifact"
    | "tool_use"
    | "tool_result"
    | "tool_approval_request"
    | "tool_approval_resolved"
    | "tool_blocked"
    | "scratch_write_denied"
    | "done"
    | "error";
  data: Record<string, unknown>;
};

// ─── Storage paths ────────────────────────────────────────────────────────────

const HISTORY_FILE = path.join(process.cwd(), "data", "task-history.jsonl");
const EVENTS_DIR = path.join(process.cwd(), "data", "task-events");

function ensureDirs() {
  const dir = path.dirname(HISTORY_FILE);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  if (!fs.existsSync(EVENTS_DIR)) fs.mkdirSync(EVENTS_DIR, { recursive: true });
}

function eventsFile(runId: string): string {
  // Sanitize: runIds are generated by us, but defense-in-depth
  const safe = runId.replace(/[^a-zA-Z0-9_-]/g, "_");
  return path.join(EVENTS_DIR, `${safe}.jsonl`);
}

// ─── Run record (header) ──────────────────────────────────────────────────────

/** Append a new task run record. Returns the same record. */
export function appendTaskRun(run: TaskRun): TaskRun {
  try {
    ensureDirs();
    fs.appendFileSync(HISTORY_FILE, JSON.stringify(run) + "\n", "utf8");
  } catch {
    // History writes must never crash the agent run.
  }
  return run;
}

/**
 * Update a task run by id. Reads → patches → rewrites. JSONL files are small
 * enough (one line per task) that this is fine for now.
 */
export function updateTaskRun(
  id: string,
  patch: Partial<TaskRun>
): TaskRun | null {
  try {
    ensureDirs();
    if (!fs.existsSync(HISTORY_FILE)) return null;
    const raw = fs.readFileSync(HISTORY_FILE, "utf8");
    let updated: TaskRun | null = null;
    const lines = raw.split("\n").filter(Boolean);
    const out: string[] = lines.map((line) => {
      try {
        const row = JSON.parse(line) as TaskRun;
        if (row.id === id) {
          updated = { ...row, ...patch };
          return JSON.stringify(updated);
        }
        return line;
      } catch {
        return line;
      }
    });
    fs.writeFileSync(HISTORY_FILE, out.join("\n") + "\n", "utf8");
    return updated;
  } catch {
    return null;
  }
}

// ─── Event log (per task) ─────────────────────────────────────────────────────

/** Append one event to the per-task event log. */
export function appendTaskEvent(runId: string, event: TaskEvent): void {
  try {
    ensureDirs();
    fs.appendFileSync(eventsFile(runId), JSON.stringify(event) + "\n", "utf8");
  } catch {
    // never crash on logging
  }
}

/** Read all events for a task. Returns empty array if file missing. */
export function readTaskEvents(runId: string): TaskEvent[] {
  try {
    const fp = eventsFile(runId);
    if (!fs.existsSync(fp)) return [];
    const raw = fs.readFileSync(fp, "utf8");
    return raw
      .split("\n")
      .filter(Boolean)
      .map((line) => {
        try {
          return JSON.parse(line) as TaskEvent;
        } catch {
          return null;
        }
      })
      .filter((e): e is TaskEvent => e !== null);
  } catch {
    return [];
  }
}

// ─── Reads ────────────────────────────────────────────────────────────────────

export type TaskFilter = {
  employeeId?: string;
  status?: TaskStatus;
  limit?: number;
};

/** Read all task runs, newest-first, with optional filtering. */
export function readTaskRuns(filter: TaskFilter = {}): TaskRun[] {
  try {
    ensureDirs();
    if (!fs.existsSync(HISTORY_FILE)) return [];
    const raw = fs.readFileSync(HISTORY_FILE, "utf8");
    const runs: TaskRun[] = raw
      .split("\n")
      .filter(Boolean)
      .map((line) => {
        try {
          return JSON.parse(line) as TaskRun;
        } catch {
          return null;
        }
      })
      .filter((r): r is TaskRun => r !== null);

    const filtered = runs.filter((r) => {
      if (filter.employeeId && r.employeeId !== filter.employeeId) return false;
      if (filter.status && r.status !== filter.status) return false;
      return true;
    });

    const reversed = filtered.reverse();
    return filter.limit ? reversed.slice(0, filter.limit) : reversed;
  } catch {
    return [];
  }
}

/** Read a single task run by id. */
export function readTaskRun(id: string): TaskRun | null {
  return readTaskRuns().find((r) => r.id === id) ?? null;
}
